### ISSUE TITLE
Notebook wrapper does not work on Jupyter-lab

### ISSUE THREAD

**Issue by issa-garcia** [templateflow/templateflow-notebooks#3]
Hello,

The last cell of 02_Visualization.ipynb is not working properly on jupyter-lab. It is working on jupyter notebook though. The problem in jupyter-lab is that the image does not flicker between the coregistered templates when hovering the mouse over it. In jupyter notebook it does.

![Screenshot from 2022-07-08 15-38-10](https://user-images.githubusercontent.com/68673381/178207043-87379739-ab63-42cd-ab70-f1e950d523e7.png)

I suspect it might have something to do with IPython.display.SVG module but I have not been able to fix it. Please let me know what information would be useful to you (versions of everything in the jupyter-lab, etc.). I am happy to provide the information that you think would help.

Regards

**Comment by oesteban** [comment]
Moved issue to nireports.
